# Generated by Django 3.0.2 on 2020-04-24 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.CreateModel(
            name='FeedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_link_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('published', models.DateField(default=datetime.date.today)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('links', models.ManyToManyField(to='home.FeedLink')),
            ],
        ),
    ]
